apiVersion: v2
name: frigate
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: 1.15.0
dependencies:
  - name: base
    version: 0.1.0
    repository: file://../base
  - name: frigate
    version: 7.8.0
    repository: https://blakeblackshear.github.io/blakeshome-charts/