baseResources:
  ingress:
    host: mc.paul-steele.com
    port: 80
  services:
    - ports:
        - port: 80
          targetPort: 8080
    - ports:
        - port: 25565
        - port: 25049
        - port: 24454
          protocol: UDP
      loadBalancerIP: 192.168.0.201
      name: minecraft
  deployment:
    nodeSelector:
      gaming: "true"
    tolerations:
      - key: "gaming"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
    containers:
      - image: pufferpanel/pufferpanel:2.6.6
        name: pufferpanel
        ports:
          - 8080
          - 25565
          - 25049
          - 24454
        volumeMounts:
          - storage
          - config
  volumes:
    - name: config
      source:
        nfs: /volume1/files/pufferpanel/config
      mountPath: /etc/pufferpanel
    - name: storage
      source:
        nfs: /volume1/files/pufferpanel/storage
      mountPath: /var/lib/pufferpanel