baseResources:
  ingress:
    host: finance.paul-steele.com
    port: 80
  services:
    - ports:
        - port: 80
          targetPort: 8080
  deployment:
    containers:
    - image: fireflyiii/core:version-6.0.27
      name: firefly
      envs:
      - name: DB_HOST
        value: 192.168.0.101
      - name: DB_USERNAME
        secretName: database-credentials
        secretKey: user
      - name: DB_PORT
        value: 3307
      - name: DB_DATABASE
        value: firefly_db
      - name: DB_CONNECTION
        value: mysql
      - name: APP_ENV
        value: local
      - name: APP_URL
        value: https://finance.paul-steele.com
      - name: TRUSTED_PROXIES
        value: '**'
      - name: DB_PASSWORD
        secretName: database-credentials
        secretKey: password
      - name: APP_KEY
        secretName: firefly-token
        secretKey: FF_APP_KEY
      volumeMounts:
      - storage
  volumes:
  - name: storage
    source:
      nfs: /volume1/files/firefly
    mountPath: /var/www/firefly-iii/storage
