apiVersion: v2
name: argo
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.17.1"
dependencies:
  - name: base
    version: 0.1.0
    repository: file://../base
  - name: argo-workflows
    version: 0.16.8
    repository: https://argoproj.github.io/argo-helm
