baseResources:
  serviceAccounts:
  - name: ci-sso
    annotations:
      workflows.argoproj.io/rbac-rule: "'admin' in groups"
  - name: ci-github
  clusterRoles:
  - name: ci-sso
    rules:
    - apiGroups:
        - argoproj.io
      resources:
        - workflows
        - workflowtemplates
        - clusterworkflowtemplates
        - cronworkflows
        - sensors
        - eventsources
      verbs:
        - get
        - list
        - create
        - watch
        - update
        - patch
        - delete
    - apiGroups:
      - dataflow.argoproj.io
      resources:
      - pipelines
      verbs:
      - get
      - list
      - create
      - watch
      - update
      - patch
      - delete
  - name: ci-submit-workflow
    rules:
    - apiGroups:
      - argoproj.io
      resources:
      - workfloweventbindings
      verbs:
      - list
    - apiGroups:
      - argoproj.io
      resources:
      - workflowtemplates
      verbs:
      - get
    - apiGroups:
      - argoproj.io
      resources:
      - workflows
      verbs:
      - create
  clusterRoleBindings:
  - name: ci-sso
    serviceAccountName: ci-sso
    serviceAccountNamespace: ci
    clusterRoleName: ci-sso
  - name: ci-github
    serviceAccountName: ci-github
    serviceAccountNamespace: ci
    clusterRoleName: ci-submit-workflow
