repositories:
- name: stable
  url: https://charts.helm.sh/stable
- name: jetstack
  url: https://charts.jetstack.io
- name: argo
  url: https://argoproj.github.io/argo-helm
- name: itzg
  url: https://itzg.github.io/minecraft-server-charts
- name: nfs-subdir-external-provisioner
  url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
- name: codecentrc
  url: https://codecentric.github.io/helm-charts
- name: metallb
  url: https://metallb.github.io/metallb
- name: twuni
  url: https://helm.twun.io
- name: zabbix-community
  url: https://zabbix-community.github.io/helm-zabbix
- name: cilium 
  url: https://helm.cilium.io/
- name: strrl.dev 
  url: https://helm.strrl.dev
- name: blakeblackshear
  url: https://blakeblackshear.github.io/blakeshome-charts/
releases:
- name: automation
  namespace: default
  chart: ./charts/nodered
- name: books
  namespace: default
  chart: ./charts/calibre
- name: audiobooks
  namespace: default
  chart: ./charts/audiobookshelf
- name: pufferpanel
  namespace: default
  chart: ./charts/pufferpanel
- name: ci
  namespace: ci
  chart: ./charts/argo
  secrets:
    - ./charts/argo/secrets.yaml
  values:
    - ./charts/argo/rbac.yaml
- name: ci-workflows
  namespace: ci
  chart: ./charts/argo-workflows
  secrets:
    - ./charts/argo-workflows/secrets.yaml
- name: dav
  namespace: default
  chart: ./charts/baikal
- name: containers
  namespace: default
  chart: ./charts/docker-registry
  secrets:
    - ./charts/docker-registry/secrets.yaml
- name: database
  namespace: default
  chart: ./charts/database
  secrets:
  - ./charts/database/secrets.yaml
- name: home
  namespace: default
  chart: ./charts/homeassistant
- name: loadbalancer
  namespace: default
  chart: ./charts/metallb
- name: loadbalancer-config
  namespace: default
  chart: ./charts/metallb-configuration
- name: music
  namespace: default
  chart: ./charts/subsonic
- name: passwords
  namespace: default
  chart: ./charts/bitwarden
- name: reader
  namespace: default
  chart: ./charts/freshrss
- name: oidc
  namespace: default
  chart: ./charts/keycloak
  secrets:
    - ./charts/keycloak/secrets.yaml
- name: storage
  namespace: default
  chart: ./charts/nfs-client-provisioner
- name: cilium
  namespace: kube-system
  chart: ./charts/cilium
- name: frigate
  namespace: default
  chart: ./charts/frigate
  secrets:
    - ./charts/frigate/secrets.yaml
- name: mosquitto
  namespace: default
  chart: ./charts/mosquitto
  secrets:
    - ./charts/mosquitto/secrets.yaml
- name: external-proxy
  namespace: default
  chart: ./charts/external-proxy
- name: deployments
  namespace: deployments
  chart: ./charts/deployments
  secrets:
  - ./charts/deployments/secrets.yaml
- name: cloudflare-tunnel
  namespace: default
  chart: ./charts/cloudflare-tunnel
  secrets:
    - ./charts/cloudflare-tunnel/secrets.yaml
