repositories:
- name: stable
  url: https://charts.helm.sh/stable
- name: jetstack
  url: https://charts.jetstack.io
- name: eddycharly
  url: https://eddycharly.github.io/tekton-helm
- name: itzg
  url: https://itzg.github.io/minecraft-server-charts
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: prometheus
  url: https://prometheus-community.github.io/helm-charts
- name: nfs-subdir-external-provisioner
  url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
releases:
- name: automation
  namespace: default
  chart: ./charts/nodered
- name: backup
  namespace: default
  chart: ./charts/duplicati
- name: books
  namespace: default
  chart: ./charts/calibre
- name: ci
  namespace: default
  chart: ./charts/tekton
  hooks:
  - events: ["prepare"]
    showlogs: true
    command: sh
    args: ["-c", "./tools/filter-crds.sh ./charts/tekton/charts/*"]
  values:
  - ./charts/tekton/rbac.yaml
  - ./charts/tekton/pipeline.yaml
  secrets:
  - ./charts/tekton/secrets.yaml
- name: certificates
  namespace: default
  chart: ./charts/certmanager
  secrets:
  - ./charts/certmanager/secrets.yaml
- name: containers
  namespace: default
  chart: ./charts/docker-registry
- name: database
  namespace: default
  chart: ./charts/database
  secrets:
  - ./charts/database/secrets.yaml
- name: cloud
  namespace: default
  chart: ./charts/nextcloud
  secrets:
  - ./charts/nextcloud/secrets.yaml
- name: finance
  namespace: default
  chart: ./charts/firefly
  secrets:
  - ./charts/firefly/secrets.yaml
- name: home
  namespace: default
  chart: ./charts/homeassistant
- name: ingress
  namespace: default
  chart: ./charts/nginx
- name: loadbalancer
  namespace: default
  chart: ./charts/metallb
- name: monitoring
  namespace: default
  chart: ./charts/prometheus
- name: music
  namespace: default
  chart: ./charts/subsonic
- name: passwords
  namespace: default
  chart: ./charts/bitwarden
- name: reader
  namespace: default
  chart: ./charts/freshrss
- name: sso
  namespace: default
  chart: ./charts/authelia
  secrets:
  - ./charts/authelia/secrets.yaml
- name: storage
  namespace: default
  chart: ./charts/nfs-client-provisioner
- name: external-dns
  namespace: default
  chart: ./charts/external-dns
- name: deployments
  namespace: deployments
  chart: ./charts/deployments
  secrets:
  - ./charts/deployments/secrets.yaml
