apiVersion: v2
name: nginx
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: 1.15.0
dependencies:
- name: ingress-nginx
  version: 4.5.2
  repository: https://kubernetes.github.io/ingress-nginx
