nginx-ingress:
  controller:
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    extraArgs: {
      default-ssl-certificate: "default/paul-steele.com"
    }
    config:
      enable-modsecurity: "false"
      enable-owasp-modsecurity-crs: "false"
    service:
      loadBalancerIP: "192.168.0.200"
