baseResources:
  ingress:
    ingressClassName: traefik
    host: books.paul-steele.com
    port: 8083
  services:
    - ports:
        - port: 8083
  deployment:
    containers:
    - image: crocodilestick/calibre-web-automated:v4.0.6
      name: calibre
      envs:
      - name: TZ
        value: America/Indianapolis
      - name: PUID
        value: "1000"
      - name: PGID
        value: "1000"
      - name: NETWORK_SHARE_MODE
        value: "true"
      ports:
      - 8083
      volumeMounts:
      - library
      - config
  cronjob:
    containers:
    - image: nouchka/sqlite3
      name: bookdump
      command:
      - sqlite3
      args:
      - /calibre-library/metadata.db
      - .backup '/backup/calibre.sq3'
      volumeMounts:
      - library
      - backup
    schedule: "0 1 * * 4"
  volumes:
  - name: library
    source:
      nfs: /volume1/files/calibre/library
    mountPath: /calibre-library
  - name: config
    source:
      nfs: /volume1/files/calibre/config
    mountPath: /config
  - name: backup
    source:
      nfs: /volume1/files/database-backup/sqlite
    mountPath: /backup
