baseResources:
  persistentVolume:
    nfs:
      path: /volume1/files/minecraft/craft-to-exile
    capacity: 10Gi
  persistentVolumeClaim:
    capacity: 10Gi

minecraft:
  imageTag: 2021.18.0
  resources:
    requests:
      memory: 6144Mi
      cpu: 3000m
  livenessProbe:
    initialDelaySeconds: 130
    periodSeconds: 5
    failureThreshold: 10
    successThreshold: 1
    timeoutSeconds: 1
  readinessProbe:
    initialDelaySeconds: 130
    periodSeconds: 5
    failureThreshold: 10
    successThreshold: 1
    timeoutSeconds: 1
  startupProbe:
    enabled: false
    failureThreshold: 30
    periodSeconds: 10

  minecraftServer:
    eula: "True"
    version: 1.16.5
    type: FABRIC
    difficulty: normal
    maxPlayers: 10
    maxWorldSize: 100000
    motd: "craft to exile"
    pvp: true
    worldSaveName: craftToExile 
    memory: 6144M
    serviceType: LoadBalancer
    loadBalancerIP: "192.168.0.202"
    rcon:
      enabled: false
      loadBalancerIP: "192.168.0.203"
  extraEnv:
    USE_AIKAR_FLAGS: true
    FABRIC_INSTALLER_URL: https://maven.fabricmc.net/net/fabricmc/fabric-installer/0.7.4/fabric-installer-0.7.4.jar
  persistence:
    dataDir:
      enabled: true
      existingClaim: minecraft-minecraft
