baseResources:
  persistentVolume:
    nfs:
      path: /volume1/files/minecraft/pixelmon-4
    capacity: 10Gi
  persistentVolumeClaim:
    capacity: 10Gi

minecraft:
  image:
    tag: java8
  resources:
    requests:
      memory: 13Gi
      cpu: 3000m
  livenessProbe:
    initialDelaySeconds: 1
    periodSeconds: 60
    failureThreshold: 30
    successThreshold: 1
    timeoutSeconds: 60
  readinessProbe:
    initialDelaySeconds: 1
    periodSeconds: 60
    failureThreshold: 30
    successThreshold: 1
    timeoutSeconds: 60
  startupProbe:
    enabled: false
    failureThreshold: 60
    periodSeconds: 10

  minecraftServer:
    eula: "True"
    version: 1.16.5
    type: FORGE
    difficulty: normal
    maxPlayers: 10
    maxWorldSize: 100000
    motd: "Pixelmon 4.0 - TemTem Version"
    pvp: true
    worldSaveName: pixelmon4
    generatorSettings: "skyislands"
    levelType: OTG
    viewDistance: 14
    forgeInstallerUrl: "https://maven.minecraftforge.net/net/minecraftforge/forge/1.16.5-36.2.39/forge-1.16.5-36.2.39-installer.jar"
    memory: 13G
    serviceType: NodePort
    nodePort: 31000
    loadBalancerIP: "192.168.0.202"
    rcon:
      enabled: false
      loadBalancerIP: "192.168.0.203"
  tolerations:
    - key: "gaming"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
  nodeSelector:
    gaming: "true"
  extraEnv:
    USE_AIKAR_FLAGS: true
    FABRIC_INSTALLER_URL: "https://maven.fabricmc.net/net/fabricmc/fabric-installer/0.11.0/fabric-installer-0.11.0.jar"
  persistence:
    dataDir:
      enabled: true
      existingClaim: minecraft-minecraft
