baseResources:
  persistentVolume:
    nfs:
      path: /volume1/files/minecraft/pixelmon-redux
    capacity: 10Gi
  persistentVolumeClaim:
    capacity: 10Gi

minecraft:
  imageTag: 1.8.0
  resources:
    requests:
      memory: 6144Mi
      cpu: 3000m

  minecraftServer:
    eula: "True"
    version: 1.12.2
    type: FORGE
    difficulty: hard
    maxPlayers: 10
    maxWorldSize: 100000
    motd: "Pixelmon-Redux"
    pvp: true
    worldSaveName: pixelmon-redux
    forgeInstallerUrl: https://maven.minecraftforge.net/net/minecraftforge/forge/1.12.2-14.23.5.2855/forge-1.12.2-14.23.5.2855-installer.jar
    memory: 6144M
    serviceType: LoadBalancer
    loadBalancerIP: "192.168.0.202"
    rcon:
      enabled: false
      loadBalancerIP: "192.168.0.203"
  extraEnv:
    USE_AIKAR_FLAGS: true
  persistence:
    dataDir:
      enabled: true
      existingClaim: minecraft-minecraft
