baseResources:
  persistentVolume:
    nfs:
      path: /volume1/files/minecraft/pixelmon-3
    capacity: 10Gi
  persistentVolumeClaim:
    capacity: 10Gi

minecraft:
  imageTag: 2021.26.0-java8-multiarch
  resources:
    requests:
      memory: 6144Mi
      cpu: 5000m
  livenessProbe:
    initialDelaySeconds: 10
    periodSeconds: 10
    failureThreshold: 60
    successThreshold: 1
    timeoutSeconds: 1
  readinessProbe:
    initialDelaySeconds: 10
    periodSeconds: 10
    failureThreshold: 60
    successThreshold: 1
    timeoutSeconds: 1
  startupProbe:
    enabled: false
    failureThreshold: 60
    periodSeconds: 10

  minecraftServer:
    eula: "True"
    version: 1.16.5
    type: FORGE
    difficulty: normal
    maxPlayers: 10
    maxWorldSize: 100000
    motd: "Pixelmon: 3"
    pvp: true
    worldSaveName: pixelmon3 
    forgeInstallerUrl: "https://maven.minecraftforge.net/net/minecraftforge/forge/1.16.5-36.2.35/forge-1.16.5-36.2.35-installer.jar"
    memory: 6144M
    serviceType: LoadBalancer
    loadBalancerIP: "192.168.0.202"
    rcon:
      enabled: false
      loadBalancerIP: "192.168.0.203"
  extraEnv:
    USE_AIKAR_FLAGS: true
  persistence:
    dataDir:
      enabled: true
      existingClaim: minecraft-minecraft
