baseResources:
    secrets:
        - name: ENC[AES256_GCM,data:vld17dh1asViJ9igc9Un7HSssjo=,iv:7NEgMJJlXBJvEcbMCOGEs/BDE8YNmDN236Xa/ggzt7E=,tag:tU8mHzClREE9iuXQGFWMhQ==,type:str]
          fields:
            cloudflare_api_token: ENC[AES256_GCM,data:chauznFGFhb/Kl+q8hlG1jLHA0NVONhLqPvege8zbR8hCrgmflkgXQ==,iv:9FPi7zjJKTijU46xFFSaFmQ+hIBqrdnioB63cqzosM8=,tag:BcOX5eVE4zFCvzfkoDu7pA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c09us2255462s4jawlctm4dw89j7js4wrctam7fp0mg3k8vznelqdnatxe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4UGtITFRGVnorcjB3MmRV
            OXBjRGxLU3hiK0hOQW02MWpVVnM5RUcyeGo4CkRZY2lkUldKaVFBZGdrMGEzUzZo
            YXlyVlkrSm9mRDh6aTNVb1JsdVdlY3MKLS0tIC83OFpwVndNRUFtOXMvdHJWM24x
            Y1V0c2trRE03TG9xVWRjdFBoUWNBQ0EKgCTibibZwop0d+oXN+3CJH9NXYg4DJWC
            gSJvAsFi7oBgoG/1KGEsk/m+WoamWVOqVegwI3pdK/FTJWO9fwxCwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-24T23:33:10Z"
    mac: ENC[AES256_GCM,data:CObcKYCsOHiTKZu8MTXfIohYYm28Y6ynWO0os5Y27YHETpprhxzDxa74wv3uUxC5KxKc0HDOIXMnu4jLwOo0V0ehrqKg0ofCDFgjL7swg0Q8tFyrHXPepIw5S5acgvfkVcFuHwd+VmgjeH1YyIhf9x0CwlEUNv84tkZALn/lldA=,iv:cq0I7kCFK/lawye9IpCmrD2zQ0S4WTJmHjN8njRcPYE=,tag:kFy0e8HJjL3BmwEhex04yg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.5.0
