baseResources:
  configmaps:
  - name: homeassistant
    data:
    - name: zha-config
      file: resources/zha.sh
    - name: zwave-config
      file: resources/zwave.sh
  ingress:
    host: home.paul-steele.com
    port: 80
  service:
    port: 80
    targetPort: 8123
  deployment:
    containers:
    - image: homeassistant/home-assistant:2023.3
      command:
      - sh
      args:
      - "-c"
      - "zha && python -m homeassistant --config /config"
      name: homeassistant
      ports:
      - 8123
      volumeMounts:
      - config
      - zha
    - image: zwavejs/zwavejs2mqtt:8.10.1
      command:
      - sh
      args:
      - "-c"
      - "zwave && node server/bin/www"
      name: zwavejs2mqtt
      ports:
      - 3000
      - 8091
      volumeMounts:
      - zwave
      - zwaveconfig
  volumes:
  - name: config
    source:
      nfs: /volume1/files/homeassistant
    mountPath: /config
  - name: zwaveconfig
    source:
      nfs: /volume1/files/zwave
    mountPath: /usr/src/app/store
  - name: zha
    source:
      configmap:
        defaultMode: 0555
        name: homeassistant
        items:
          key: zha-config
          path: zha
    mountPath: /usr/bin/zha
    subPath: zha
  - name: zwave
    source:
      configmap:
        defaultMode: 0555
        name: homeassistant
        items:
          key: zwave-config
          path: zwave
    mountPath: /usr/bin/zwave
    subPath: zwave
