apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.relay.hostname }}
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.relay.lanIP }}
  selector:
    app: {{ .Values.relay.hostname }}
  ports:
    - name: relay
      port: {{ .Values.relay.port }}
      targetPort: {{ .Values.relay.port }}
      protocol: UDP
