#3333:raw:0:/dev/ttyUSB0:115200 8DATABITS NONE 1STOPBIT
#3334:raw:0:/dev/ttyUSB1:57600 8DATABITS NONE 1STOPBIT
connection: &zwave
  accepter: ipv4,tcp,3333
  enable: on
  connector: serialdev,/dev/ttyUSB0,115200n81,local,nobreak
  options:
    kickolduser: true
  
connection: &zigbee
  accepter: ipv4,tcp,3334
  enable: on
  connector: serialdev,/dev/ttyUSB1,57600n81,local,nobreak
  options:
    kickolduser: true
