apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: ci-build
spec:
  serviceAccountName: ci-workflow
  entrypoint: build
  volumeClaimTemplates: 
  - metadata:
      name: workdir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
  templates:
    - name: build
      steps:
      - - name: clone
          template: git-clone
    - name: git-clone
      volumeMounts: 
        - name: workdir
          mountPath: /git
      container:
        image: alpine/git
        command: 
          - "git"
        args:
          - "clone"
          - "{{"{{"}}workflow.parameters.git_url{{"}}"}}"
    - name: build
      container:
        image: gcr.io/kaniko-project/executor
        args:
          - "--destination=registry.paul-steele.com/{{"{{"}}workflow.parameters.docker_registry{{"}}"}}:{{"{{"}}workflow.parameters.sha{{"}}"}}"
    - name: prepare-manifest
      container:
      image: loicmahieu/alpine-envsubst
      command: "sh"
      args:
        - "-c"
        - "envsubst < k8s.template.yaml > k8s.yaml"
    - name: deploy
      container:
      image: lachlanevenson/k8s-kubectl:v1.15.0
      command: "kubectl"
      args:
      - "apply"
      - "-f"
      - "k8s.yaml"
---
{{- range $index, $repository:= .Values.repositories }}
apiVersion: argoproj.io/v1alpha1
kind: WorkflowEventBinding
metadata:
  name: event-binding-{{$repository.name}}
spec:
  event:
    # metadata header name must be lowercase to match in selector
    selector: payload.repository.url == "{{$repository.url}}" 
  submit:
    workflowTemplateRef:
      name: ci-build 
    arguments:
      parameters:
        - name: git_url
          valueFrom:
            event: payload.repository.url
---
{{- end }}
