apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: ci-build
spec:
  serviceAccountName: ci-workflow
  entrypoint: build
  volumeClaimTemplates: 
  - metadata:
      name: workdir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
  templates:
    - name: build
      steps:
      - - name: clone
          template: git-clone
      - - name:  build
          template: build-container
    - name: git-clone
      container:
        image: alpine/git
        command: 
          - "git"
        args:
          - "clone"
          - "{{"{{"}}workflow.parameters.git_url{{"}}"}}"
        volumeMounts:
          - name: workdir
            mountPath: /git
    - name: build-container
      container:
        image: gcr.io/kaniko-project/executor
        command:
          - "/kaniko/executor"
        args:
          - "--dockerfile=/workspace/{{"{{"}}workflow.parameters.git_name{{"}}"}}/Dockerfile"
          - "--context=dir:///workspace/{{"{{"}}workflow.parameters.git_name{{"}}"}}"
          - "--destination=registry.paul-steele.com/{{"{{"}}workflow.parameters.git_name{{"}}"}}:{{"{{"}}workflow.parameters.git_sha{{"}}"}}"
        volumeMounts:
          - name: workdir
            mountPath: /workspace
          - name: docker-registry
            mountPath: /kaniko/.docker/config.json
            subPath: config.json
      volumes:
        - name: docker-registry
          secret:
            secretName: registry.paul-steele.com
            items:
              - key: .dockerconfigjson
                path: config.json
    - name: prepare-manifest
      container:
      image: loicmahieu/alpine-envsubst
      command: "sh"
      args:
        - "-c"
        - "envsubst < k8s.template.yaml > k8s.yaml"
    - name: deploy
      container:
      image: lachlanevenson/k8s-kubectl:v1.15.0
      command: "kubectl"
      args:
      - "apply"
      - "-f"
      - "k8s.yaml"
---
{{- range $index, $repository:= .Values.repositories }}
apiVersion: argoproj.io/v1alpha1
kind: WorkflowEventBinding
metadata:
  name: event-binding-{{$repository.name}}
spec:
  event:
    # metadata header name must be lowercase to match in selector
    selector: payload.repository.url == "{{$repository.url}}" 
  submit:
    workflowTemplateRef:
      name: ci-build 
    arguments:
      parameters:
        - name: git_url
          valueFrom:
            event: payload.repository.url
        - name: git_name
          valueFrom:
            event: payload.repository.name
        - name: git_sha
          valueFrom:
            event: payload.after
---
{{- end }}
