apiVersion: v2
name: external-dns
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: 1.16.0
dependencies:
- name: base
  version: 0.1.0
  repository: file://../base
- name: external-dns
  version: 6.7.2
  repository: https://charts.bitnami.com/bitnami
