external-dns:
  sources:
  - ingress
  provider: cloudflare
  cloudflare:
    secretName: cloudflare-api-token
    email: "paul@paul-steele.com"
    proxied: true
  txtOwnerId: "home-lab"
  logLevel: debug
  metrics:
    enabled: false
    serviceMonitor:
      enabled: false
