apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: ci-build
spec:
  serviceAccountName: ci-workflow
  entrypoint: build
  onExit: exit-handler
  volumeClaimTemplates: 
  - metadata:
      name: workdir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
  templates:
    - name: build
      steps:
      - - name: clone
          template: git-clone
      - - name:  build
          template: build-container
      - - name:  prepare-manifest
          template: prepare-manifest 
      - - name:  deploy
          template: deploy
    - name: git-clone
      container:
        image: alpine/git
        command: 
          - "sh"
        args:
          - "-c"
          - "git clone https://$GITTOKEN@github.com/{{"{{"}}workflow.parameters.git_url{{"}}"}}.git"
        env:
          - name: GITUSER
            valueFrom:
              secretKeyRef:
                name: github-credentials
                key: username 
          - name: GITTOKEN
            valueFrom:
              secretKeyRef:
                name: github-credentials
                key: token 
        volumeMounts:
          - name: workdir
            mountPath: /git
    - name: build-container
      container:
        image: gcr.io/kaniko-project/executor
        command:
          - "/kaniko/executor"
        args:
          - "--dockerfile=/workspace/{{"{{"}}workflow.parameters.git_name{{"}}"}}/Dockerfile"
          - "--context=dir:///workspace/{{"{{"}}workflow.parameters.git_name{{"}}"}}"
          - "--destination=registry.paul-steele.com/{{"{{"}}workflow.parameters.git_name{{"}}"}}:{{"{{"}}workflow.parameters.git_sha{{"}}"}}"
        volumeMounts:
          - name: workdir
            mountPath: /workspace
          - name: docker-registry
            mountPath: /kaniko/.docker/config.json
            subPath: config.json
      volumes:
        - name: docker-registry
          secret:
            secretName: registry.paul-steele.com
            items:
              - key: .dockerconfigjson
                path: config.json
    - name: prepare-manifest
      container:
        image: loicmahieu/alpine-envsubst
        command: 
          - "sh"
        env:
          - name: BUILD_TAG
            value: "{{"{{"}}workflow.parameters.git_sha{{"}}"}}"
        args:
          - "-c"
          - "envsubst < /workspace/{{"{{"}}workflow.parameters.git_name{{"}}"}}/k8s.template.yaml > /workspace/{{"{{"}}workflow.parameters.git_name{{"}}"}}/k8s.yaml"
        volumeMounts:
          - name: workdir
            mountPath: /workspace
    - name: deploy
      container:
        image: lachlanevenson/k8s-kubectl:v1.15.0
        command: 
          - "kubectl"
        args:
          - "apply"
          - "-f"
          - "/workspace/{{"{{"}}workflow.parameters.git_name{{"}}"}}/k8s.yaml"
        volumeMounts:
          - name: workdir
            mountPath: /workspace
    - name: exit-handler
      steps:
        - - name: exit-handler-success
            template: exit-sender
            arguments:
              parameters:
                - name: color
                  value: "65280"
            when: "{{"{{"}}workflow.status{{"}}"}} == Succeeded"
        - - name: exit-handler-fail
            template: exit-sender
            arguments:
              parameters:
                - name: color
                  value: "16711680"
            when: "{{"{{"}}workflow.status{{"}}"}} != Succeeded"
    - name: exit-sender
      inputs:
        parameters:
          - name: color
      container:
        image: curlimages/curl:7.85.0
        env:
          - name: DISCORD_WEBHOOK
            valueFrom:
              secretKeyRef:
                name: argo-notifications
                key: discord-webhook
        command:
          - "sh"
          - "-c"
        args:
          - "curl -H \"Content-Type: application/json\" -d '{ \"embeds\": [ { \"color\": {{"{{"}}inputs.parameters.color{{"}}"}}, \"title\": \"Pipeline Results\", \"fields\": [{\"name\": \"{{"{{"}}workflow.name{{"}}"}}\", \"value\": \"{{"{{"}}workflow.parameters.git_name{{"}}"}}\", \"inline\": true},{\"name\": \"Status\", \"value\": \"{{"{{"}}workflow.status{{"}}"}}\", \"inline\": true }, {\"name\": \"Duration\", \"value\": \"{{"{{"}}workflow.duration{{"}}"}}\", \"inline\": true }, { \"name\": \"Failures\", \"value\": {{"{{"}}workflow.failures{{"}}"}} }]}]}' $DISCORD_WEBHOOK"
---
{{- range $index, $repository:= .Values.repositories }}
apiVersion: argoproj.io/v1alpha1
kind: WorkflowEventBinding
metadata:
  name: event-binding-{{$repository.name}}
spec:
  event:
    # metadata header name must be lowercase to match in selector
    selector: payload.repository.url == "{{$repository.url}}" 
  submit:
    workflowTemplateRef:
      name: ci-build 
    arguments:
      parameters:
        - name: git_url
          valueFrom:
            event: payload.repository.full_name
        - name: git_name
          valueFrom:
            event: payload.repository.name
        - name: git_sha
          valueFrom:
            event: payload.after
---
{{- end }}
