cloudflare-tunnel-ingress-controller:
  cloudflare:
    accountId: ENC[AES256_GCM,data:7wyTtarl1UgYYEsS6JEW6E7tjT/I9yXm6riFPXiKLkc=,iv:k6DA7w2dW7tVT0w5XwgoF8kGFTBCZlFwF1RhF5Y8y08=,tag:hmenpe7llX2f/XQ7oAF0EA==,type:str]
    tunnelName: ENC[AES256_GCM,data:s4h9ITvwus0wpSLkQQ==,iv:L3bPOJaG+RaiPGslNFUD2oNdLE4dL+DS3Eu7izJlOZk=,tag:Kzl1LW62UyWOGNQhvv2G6w==,type:str]
    apiToken: ENC[AES256_GCM,data:agEr2f0LYuIdUrwoxgDMG+7BHoJH4QNlBUeywO4l/qr1+3MxDwLyUA==,iv:MEyef08Ni4mFa3M47fmuc1OR8NkGPvocJM+HfnXCW4k=,tag:NyvwCzKU4+081UYSbotLNQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1c09us2255462s4jawlctm4dw89j7js4wrctam7fp0mg3k8vznelqdnatxe
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWWFsTHp0MEJCcFQrWERi
        TGRIYnlzVjliVXJmaUVSdGlhUTNTbytlUEVrClo0TTg0aTNNRmRUWWc0MmduSTU4
        bVVTaHBRUXNTYmRrSDluQTRNekhHYmsKLS0tIC9tems4a0xiR1JiRkFGV2Rad2tZ
        b2ZKN0paMENKcm5PbDFhYnozWG1sbDgKDcWNgwt5kdk1e8X7xEk8wROjAkhz0EaI
        dgxkUthdWQHC900YHZRW7Nb4G2eXZpnfTIy9giiklw1VjbLGPP0sPg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2023-12-30T19:49:25Z"
  mac: ENC[AES256_GCM,data:C+O51QCgAuk+A+ndI2uOQa1RtIMX6H8HEtdRwzt+G3kZT1eBOWs8WvOBHyl4IAI5iHk9kvkMiRD9Ycx6+Um3aVmbz/VY7YSHV/GY0LYcRlGukkYAqXX2zTeIuZIf4ZuLTk6THmtrIiZyD1JKhX1coHazDIcPGD0zQPHlj38AFqM=,iv:bLb4MPRAv5Cv8h2xeRhBv+Q+MJa/3IfHAVrfHipB5i4=,tag:neasv2LcGtuSlS62PR8q8g==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1