tailscale-operator:
    oauth:
        clientId: ENC[AES256_GCM,data:Vha7ttpIw0NWUfyNnv2SEZw=,iv:1JsynVxmk8ub2ttTDwMjgeaLx8+grZyWLGt3DvK4tzc=,tag:Eel6lEK0b5y8PQwIetB6NA==,type:str]
        clientSecret: ENC[AES256_GCM,data:PYOYHpTH6rrdAJ97dN9wUHWPupjLXCCvY0o0l/nh6DCgo2HOpYJBUGjBsaLxXMV0Q9QNyuMFA7fycKE3Kc56pA==,iv:tdD38xX/yVTtSNd5jLHpX9FxtHEvPrbOjI68N5GYw3k=,tag:drgbOZVZmy7SluBBxRqH6Q==,type:str]
sops:
    age:
        - recipient: age1c09us2255462s4jawlctm4dw89j7js4wrctam7fp0mg3k8vznelqdnatxe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsSU1YcW5VS0Mydlo1Qmhu
            alVBVUxPaVRRWlViaVpvL2I3bEI0THB3WldjCjh3ZjVvTml5cUZLQ0piRTliMUdQ
            TXFxUlQxdi9WcmZGd1Z5NjlyZ1dvb0UKLS0tIE9QaWV3K2ZreEZmcDFtVS9wblZh
            MXdCdldjZzNyMmlNNW1YcXUwUmdmd0UK2aeq1vBqiKzXCGvQ5NOKdqwIotWpa0Wr
            5xpM7+5s78nCh1tM4HAGUSphUdUceHtb9R9+/JC8sXaGWQihnI4Z0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T12:25:38Z"
    mac: ENC[AES256_GCM,data:VFrWA+PqqMD1Qa7DGvmfh3pQwiNFlY246OMbR+aiQXm+YJm3a/D9pG2yK3uFPBkBRW9/IVwD6TdZDizS+5dv4FMhFp0g7/TivvgYm8i0Igea48qWIDAzOQCoGa9ghYa15ohP2Av2XF1AbxDMUbBG3DafjJYkk9VHRHcwucBvRcA=,iv:sIKeLxykoF129J8pCG5uShwv1yQ/bpc91a53C0egiNU=,tag:EOYYYtYsiMOSjcalom2RlQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
