baseResources:
  ingress:
    host: board.paul-steele.com
    port: 8000
  services:
    - ports:
        - port: 8000
  deployment:
    containers:
    - image: mattermost/focalboard:7.2.1
      name: focalboard
      ports:
      - 8000
      volumeMounts:
      - storage
  cronjob:
    containers:
      - image: nouchka/sqlite3
        name: passworddump
        command:
          - sqlite3
        args:
          - /data/focalboard.db
          - .backup '/backup/focalboard.db'
        volumeMounts:
          - storage
          - backup
    schedule: "0 1 * * 4"
  volumes:
  - name: storage
    source:
      nfs: /volume1/files/focalboard
    mountPath: /data
  - name: backup
    source:
      nfs: /volume1/files/database-backup/sqlite
    mountPath: /backup
