apiVersion: v2
name: prometheus
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: 1.15.0
dependencies:
- name: kube-prometheus-stack
  version: 16.12.0
  repository: https://prometheus-community.github.io/helm-charts
