kube-prometheus-stack:
  alertmanager:
    serviceAccount:
      create: true
      name: ""
    ingress:
      enabled: false
    service:
      type: ClusterIP
  grafana:
    enabled: true
    adminPassword:
    defaultDashboardsEnabled: true
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        external-dns.alpha.kubernetes.io/hostname: metrics.paul-steele.com
        external-dns.alpha.kubernetes.io/target: "paulsteelehome.duckdns.org"
      hosts:
        - metrics.paul-steele.com
      tls:
        - hosts:
           - metrics.paul-steele.com
    sidecar:
      dashboards:
        enabled: true
        label: grafana_dashboard
      datasources:
        enabled: true
        label: grafana_datasource
  coreDns:
    enabled: true
    service:
      port: 9153
      targetPort: 9153
      selector:
        k8s-app: kube-dns
  kubeDns:
    enabled: false
