apiVersion: v2
name: docker-registry
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: 1.15.0
dependencies:
- name: base
  version: 0.1.0
  repository: file://../base
- name: docker-registry
  version: 2.2.2
  repository: https://helm.twun.io
