{{- define "base.ingress" -}}
{{- if .Values.baseResources.ingress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: '0'
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.baseResources.ingress.host }}
    external-dns.alpha.kubernetes.io/target: "paulsteelehome.duckdns.org"
    {{- if .Values.baseResources.ingress.auth }}
    nginx.ingress.kubernetes.io/auth-url: "https://sso.paul-steele.com/api/verify"
    nginx.ingress.kubernetes.io/auth-signin: "https://sso.paul-steele.com/"
    {{- end }}
  name: {{ include "base.name" . }}
spec:
  rules:
  - host: {{ .Values.baseResources.ingress.host }}
    http:
      paths:
      {{- if .Values.baseResources.ingress.extraPaths }}
      {{- $root := . -}}
      {{- $serviceName := .Values.baseResources.ingress.serviceName -}}
      {{- range $index, $path := .Values.baseResources.ingress.extraPaths }}
      - backend:
          service:
            name: {{ default ( include "base.name" $root ) $serviceName }}
            port: 
              number: {{ $path.port }}
        path: {{ $path.path }}
        pathType: Prefix
      {{- end }}
      {{- end }}
      - backend:
          service:
            name: {{ default ( include "base.name" . ) .Values.baseResources.ingress.serviceName }}
            port: 
              number: {{ .Values.baseResources.ingress.port }}
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - {{ .Values.baseResources.ingress.host }}
{{- end }}
{{- if .Values.baseResources.ingresses }}
{{- range $index, $ingress := .Values.baseResources.ingresses }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: '0'
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
    external-dns.alpha.kubernetes.io/hostname: {{ $ingress.host }}
    external-dns.alpha.kubernetes.io/target: "paulsteelehome.duckdns.org"
    {{- if $ingress.auth }}
    nginx.ingress.kubernetes.io/auth-url: "https://sso.paul-steele.com/api/verify"
    nginx.ingress.kubernetes.io/auth-signin: "https://sso.paul-steele.com/"
    {{- end }}
  name: {{ $ingress.name }}
spec:
  rules:
  - host: {{ $ingress.host }}
    http:
      paths:
      - backend:
          service:
            name: {{ $ingress.serviceName }}
            port: 
              number: {{ $ingress.port }}
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - {{ $ingress.host }}
---
{{- end }}
{{- end }}
{{- end -}}
