{{- define "base.serviceAccounts" -}}
{{- range $index, $serviceAccount:= .Values.baseResources.serviceAccounts }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceAccount.name }}
  {{- if $serviceAccount.namespace }}
  namespace: {{ $serviceAccount.namespace }}
  {{- end }}
  {{- if $serviceAccount.annotations }}
  annotations:
  {{- range $key, $value := $serviceAccount.annotations }}
    {{$key}}: "{{$value}}"
  {{- end }}
  {{- end }}
---
{{- end }}
{{- end -}}
