{{- define "base.service" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "base.name" . }}
spec:
  ports:
  - port: {{ .Values.baseResources.service.port }}
    protocol: TCP
    targetPort: {{ default .Values.baseResources.service.port .Values.baseResources.service.targetPort }}
{{- if .Values.baseResources.service.extraPorts }}
    name: 'default'
  - port: {{ .Values.baseResources.service.extraPorts.port }}
    name: 'extra'
    protocol: TCP
    targetPort: {{ .Values.baseResources.service.extraPorts.port }}
{{- end}}
{{- if .Values.baseResources.service.extraPorts1 }}
  - port: {{ .Values.baseResources.service.extraPorts1.port }}
    name: 'extra1'
    protocol: TCP
    targetPort: {{ .Values.baseResources.service.extraPorts1.port }}
{{- end}}
{{- if .Values.baseResources.service.extraPorts2 }}
  - port: {{ .Values.baseResources.service.extraPorts2.port }}
    name: 'extra2'
    protocol: TCP
    targetPort: {{ .Values.baseResources.service.extraPorts2.port }}
{{- end}}
  selector:
    app: {{ include "base.name" . }}
  {{- if .Values.baseResources.service.loadBalancerIP }}
  type: LoadBalancer
  loadBalancerIP: {{ .Values.baseResources.service.loadBalancerIP }}
  {{- end }}
{{- end -}}
