{{- define "base.services" -}}
{{- range $index, $service:= .Values.baseResources.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ default (include "base.name" $) $service.name }}
  {{- if $service.annotations }}
  annotations:
    {{- range $key, $val := $service.annotations }}
    {{ $key }}: "{{ $val }}"
    {{- end }}
  {{- end }}
spec:
  ports:
  {{- range $index, $port:= $service.ports }}
  - port: {{ $port.port }}
    protocol: {{ default "TCP" $port.protocol }}
    targetPort: {{ default $port.port $port.targetPort }}
    name: port-{{ $index }}
  {{- end }}
  {{- if not $service.hideSelector }}
  selector:
    app: {{ include "base.name" $ }}
  {{- end }}
  {{- if or $service.loadBalancerIP $service.loadBalancerClass }}
  type: LoadBalancer
  {{- end }}
  {{- if $service.loadBalancerIP }}
  loadBalancerIP: {{ $service.loadBalancerIP }}
  {{- end }}
  {{- if $service.loadBalancerClass }}
  loadBalancerClass: {{ $service.loadBalancerClass }}
  {{- end }}
---
{{- end -}}
{{- end -}}
