baseResources:
    secrets:
        - name: ENC[AES256_GCM,data:d6cbfchkjcCEI4PfVUfcpyr9,iv:70emOVjlMMgAwbE4vziHGpsb3aTI3ETydBTn2ZT+y0g=,tag:VOTb3Wc1v4Md5NKfMix/4Q==,type:str]
          multilineFields:
            config.json: ENC[AES256_GCM,data:lIcnrI8CcP+YsaC92u5gm6xerO4K97Uui/46jCAUb5LF2UJEeGKLSXKh3lW/xkjHLiRj+FAbm+g+mBAJpSQx6xXq8n2wkG7XlMiDMyK6Y/HzFH1/eYTSyTAh2R3y6fAJf198aNrsSfKAYzmRYQ==,iv:5E78wxi4CokCtKxXKGAWmaKayOu5x/Ag2gXkxYhfzTU=,tag:nz9ph6J5QGP5t/qbT7BKdg==,type:str]
        - name: ENC[AES256_GCM,data:WKiV,iv:GwT8Wq0btJVYXnwUhcy0VJaaY0vpyOUIXnB7HSxRT8c=,tag:7Z7pTjKc2v1jvNNsSyJ2DQ==,type:str]
          fields:
            JwtSecurityKey: ENC[AES256_GCM,data:nzYzEgifvpk3lIS1PzoYAJX0HXpVHLFy7ewgjlnilAZVvid99/eT290bFYYK7fedE3nCBCnThWc+j1i0TYaV2WxOWV5ThlL6L3AD3SejY4dLLdH89jdRfQbMXvddOx+bEM/6jSZGdDQ6XCsC3/aF750txOkcbPG2Y7aKVl95py4=,iv:i9OEQ+74AJlytLSopwiaGfk3ZcxkEe6Y2iiqX5cVw40=,tag:LbH2YC77hQ0Sp7IaDCTNNw==,type:str]
        - name: ENC[AES256_GCM,data:iEotIJ/qJitf1A==,iv:hmDBFg2w0wLwok/JbDP+fDObclaATID7FjB+ild21xk=,tag:FYkgY8duhyhrqQ6jxEYOIw==,type:str]
          fields:
            JwtSecurityKey: ENC[AES256_GCM,data:O1YXuyoAEGhKVE9i4U+lo4MvrKShsi4xNW33AL/pENH8SyJl26Ye2/aWOPuJjMhryTiXOzCE8JHT0isHDgYQV+PS/c2vSngwG0RuXwzgp+69Z9cUe6rrSeGEervIOvWcE2/ThvTwcakaVmQzSqalrU3m3B5O62TFLmRj0sk/lR0=,iv:AGFNRhar/36I0QlHC2E1/bk+8HcIvT4OEo3YIAgE558=,tag:DYnt0USAQvNevBh8F5gKlg==,type:str]
            defaultUserName: ENC[AES256_GCM,data:Ok0=,iv:4Fb3nWkloKPDHW/WQAV8onvE4OMeH3YG+oexEQiFnso=,tag:3qK/6BPx5zZxtyrCE8UEmQ==,type:str]
            defaultUserPass: ENC[AES256_GCM,data:JNAL7xHJagQW+gY9jbSv8VprgJFBvnnnGkzlCAwRabAhFZ0sWNLRsbhWZuq3QNg=,iv:mCDvOkso0q6mn4YovmS26P+lcBHcPMRezbs0/OYKRDQ=,tag:EmqUschylTj/h0d1DA3NdQ==,type:str]
        - name: ENC[AES256_GCM,data:lQzYBVzC1I8=,iv:woMlPkkaWSR4wlRJsPUYZfYqW5I2+6qR5/VfJv2v4Zg=,tag:S9SiAinG/ak5rnlNpjicoA==,type:str]
          fields:
            SqsQueueUrl: ENC[AES256_GCM,data:ZSgC7PPFKFN6xjFKm5+vrWdfko53fpjHqdv36EMeTO98VJYswzkxtDE/QODuMfXnRiKET9Dk,iv:ATnBLhkT0kM9FrFjdq4RB4NWMWDWL4xKdDj1x+OabyM=,tag:VGChjzW1NCz8BeplXgabag==,type:str]
            AwsAccessKey: ENC[AES256_GCM,data:Al1Es+sXJg5wZU5dE17rEdjmQFg=,iv:yes8B0j1V8TMbGyEMEGTvsKDiWD+rlP+b7TdYufdOTw=,tag:erEI6kWCUD5h6nTQoaK13A==,type:str]
            FireflyHost: ENC[AES256_GCM,data:FdlpjR1cc6k4LQXqHOiAHeLj4GPsP+qtBRbHuQVXKA==,iv:TBKTfLmOFZDinbIIXRxiM7jV8nmHvONuXmwfplzb4Ts=,tag:FGAutUgEwUHX5MF3aFBVXg==,type:str]
            AwsSecretAccessKey: ENC[AES256_GCM,data:zegBV/HZT4hlqVR/I0aHJ+RFeqnTYTYettGPv8irE07rykoq6kYJHg==,iv:G8PdjQbR46ToWmQZPSS+12LI8bjRRHpHCvg/eQC+JgE=,tag:c4Ux9gSnT9mrrdKJhg5VJw==,type:str]
            FireflyToken: ENC[AES256_GCM,data:B5W9J7rec+/mDlkmZGRoO+d+iWDu7LAkAIY2Eryb9v1LpShmqI2WM0MYT/ApfEi4myhLqBthIuenHLJQhHXGfEhRPDkdEhMslJJwE7C0u8yguWJaN1OMX4f2w0EUEdY5iGGDKNSxSMEHLMZTCaQ9UCkp3acScHbu5znyM81tRt59OX+Viv+/CDwt+rQBKMdAuI0XNvReky+f3PFpqZdKrjsEtZBNxl3IJWFW5BDAVn+5QWcjLEUelfhyc/Yd7y2IqR2CugVtw+cSMJoJH4E87sUOyvFIyG2dtEcwYCOgU8Vg6lSmufP3Dfh9orX9TlvvwfT4qYXAOO9BPWiCUYQzKHiE/SV5B6+mlq3jeGUx1rRaERwO8GuDzQj7ba57MJ3VDIv5NVZYyrkO/tnKRRUYagiVrn27l3HmO1U75QKFmjSDar0p9W7qVFYXf5WwRMWGJ+HGSVQmx5DrxkDa5fg1N2T2lV/7u64dRFS2IWHl5eI54lvHjOOdwT/Hv8vP+uvYRHJjhNe+S+MGigIP+Rig8BDzV2U5XesF+5LuXRAUWN6qQuLQvDRYddsx/EnZAOCvjqNPrcwjTD2EAUNxyfhuK4pJJHZty3HGuBYAXet6fF7tcNIXCqeGIoHo0XHXCBf5mJUcoKVdIp5o/SJOPQnZGofLh7z1Uz/MXSWDY2vHZulNiCaluUR0jK2HoJB5TmwgLj6Z9ozbhG8d29/Tj89QBbNAaaupQXMlaUKHo5etERuO9SxbN5VQE0W9CVRrPRYeFYsluWpQWLDfHJpCFmCmQ2Gxiy4agCZ1hU9X+TDahPF7m81bo4tPFDRlV62BBDhXMsesXcrTTtLRwmuNC2SRrg0AAa2dnKLpjB/prGOkIsG/1scwwCoaMZ3J53fYfd0cl9LBqoG0OCfW17tY+noqTY6Z2hEWv4bM7xBtTinyotmuNXd5jP3B6kWizbzdYxfg/rCBeuZGAjXAnmXTZwgs8QDwtqBgg7UG1T1Lzyp2t5hO9Dnu4TI0TiP/+pZjNntUcGy028n+7c2MDo3HgxR93NVXIDonTPpCope8YPqfHJimwo8iLiWp83sNrRhW5oOYEbI9BTtONL4tTUQPelwmByi7PISOyQkDf+z1e9hGpkCIpGiblPKlgfQ0yyxhdd98cQdO6MNb03WbFj13I99+Hwv5iut3pKjp+l1P+8RPOhShKGBohbKET8zAYhtbSBJSd9LnUbq0D5z82n4TIkb9szTnFYrPop7Kti+GWZUujBuNJe7PWXnD7tHW+vJuS86SNoENy91a2Vr0zNFSFZ8LXuYfXw==,iv:ocOroGFBJGfUdN6nfDJfVOEYbjVrN9Izum2X5cBPQB0=,tag:Fb2w+pqsvNDdCrDgpiu9gQ==,type:str]
            DiscordBotKey: ENC[AES256_GCM,data:W2gBBBH3FHwgl+UCpT9VgmlhTHBuOBttrbuchwWs5gl+kzSkVxtkOM+fgIrHwhg2Z9OfjQyKUwRQGCoE0rJF7c7/oAig/xea,iv:yFEy0Ldz48c2VazruGX20ymvjkTaP0dGA6Gnmk9wzjw=,tag:ihCAAxAviuZXfJ+gO0nyvw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-11-02T00:16:57Z"
    mac: ENC[AES256_GCM,data:m9CmnUNV+BWHUTOcBpIXG0WcU6YIlwGC/YWFijBO1bR6wpU1/8obE5MZA1ykqKXh7l6xqV+QKCEyhNj7afWdIHeE54XHkbN4xY3SpGPCKjiwvUM+YOLxwxq6aivGz4JPR3vw5XnYIjFXneLc4QmBlC57y64IHeivZ6Q/oi3+w1g=,iv:S01UhEzAm6XPgSPIOCOkRgxSkyhRo9LiSoJVziiXGtk=,tag:LEIXA4xx71z61Cq+XklH0w==,type:str]
    pgp:
        - created_at: "2022-11-02T00:16:56Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA1Biv9gnCd8SAQf/TypFrrAE6IABNX2a6+4XoJfV5YtxuNXOZLWQWoirhrwk
            p/anR+sbJe81U2rgPE+FzUGXs6ABqtHRH+LQ4F4/Bbp7s4YNVCq4Yv8Ws5BwFQuq
            Adc5TRBoZrmBE1jgXoomOyrGblNL0jyyGTj8EKdT9uI79s1ZM8SZ4yJMftey7H4a
            jA3xJKBsqGHT0M9Q/6Z87Wr6/qf/K4QTLpHbwzePUNaQQ1SncvAR3k9/K6mygxjA
            mPDaBwokZaRYAsAYBEOmAC4kk2z94sZUvvQXxKeOs+8Upxmz2NQx1FOA9qnadsJ6
            PeSODjAxNQ4v+o4lEwEo8CMKoF7PqQupxWYkNJ+12dJcAea2ez2mZYJWUTAFxh/Q
            ZqZEOeIa1i1iyYbBynoJX42lNH23qZ1aWxbaGxiJRJt3tIv0kxyLFX6I+Ef+tpJS
            Bqdi8GPTmAiYOQ7ncGz4HXZ+Hfk5rWHbc9w5h9Q=
            =1Kws
            -----END PGP MESSAGE-----
          fp: 02B688797D1B649A6FB352756E8AC191164F2E1D
    unencrypted_suffix: _unencrypted
    version: 3.7.3
