server {
    listen 80;
    server_name paul-steele.com;

    location = /.well-known/webfinger {
        default_type application/jrd+json;
        return 200 '{"subject":"acct:paul@paul-steele.com","links":[{"rel":"http://openid.net/specs/connect/1.0/issuer","href":"https://oidc.paul-steele.com/auth/realms/master"}]}';
    }

    location / {
        return 404;
    }
}
