baseResources:
  ingress:
    host: cloud.paul-steele.com
    port: 80
  services:
    - ports:
        - port: 80
  deployment:
    containers:
    - image: nextcloud:21.0.0
      name: nextcloud
      envs:
      - name: MYSQL_HOST
        value: 192.168.0.101:3307
      - name: MYSQL_USER
        secretName: database-credentials
        secretKey: user
      - name: MYSQL_DATABASE
        value: nextcloud
      - name: MYSQL_PASSWORD
        secretName: database-credentials
        secretKey: password
      - name: NEXTCLOUD_ADMIN_PASSWORD
        secretName: nextcloud-admin-pass
        secretKey: NEXTCLOUD_ADMIN_PASS
      - name: NEXTCLOUD_ADMIN_USER
        value: paul
      - name: NEXTCLOUD_TRUSTED_DOMAINS
        value: cloud.paul-steele.com
      - name: NEXTCLOUD_UPDATE
        value: '1'
      ports:
      - 80
      volumeMounts:
      - storage
  volumes:
  - name: storage
    source:
      nfs: /volume1/files/nextcloud
    mountPath: /var/www/html
