baseResources:
  ingress:
    host: board.paul-steele.com
    port: 8000
  service:
    port: 8000
  deployment:
    containers:
    - image: mattermost/focalboard:7.2.1
      name: focalboard
      ports:
      - 8000
      volumeMounts:
      - storage
  volumes:
  - name: storage
    source:
      nfs: /volume1/files/focalboard
    mountPath: /data
