---
- hosts: masters
  become: true
  tasks:
  - name: Install ser2net packages
    apt:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
        - ser2net
            
  - name: ensure ser2net directory exists
    file:
      path: /etc/ser2net
      state: directory
      
  - name: Update ser2net config
    copy:
      src: files/ser2net.yaml
      dest: /etc/ser2net/ser2net.yaml
      
  - name: enable ser2net
    ansible.builtin.systemd:
      name: ser2net
      enabled: true
      state: started
      masked: no
      