---
- hosts: workers
  become: true
  tasks:
    - name: Copy the join command to server location
      copy: src=join-command.sh dest=/tmp/join-command.sh mode=0777

    - name: Join the node to cluster
      command: sh /tmp/join-command.sh
    
