baseResources:
  clusterIssuer:
    accessKeyID: AKIA5IJM3JBT4OHKN63G
    secretName: cloudflare-api-token
  certificates:
  - name: paul-steele.com
    namespace: default
    domains:
    - '*.paul-steele.com'
  - name: twitchplaysdnd.com
    namespace: deployments
    domains:
      - 'twitchplaysdnd.com'
cert-manager:
  podDnsPolicy: "None"
  podDnsConfig:
    nameservers:
      - "1.1.1.1"
  webhook:
    enabled: false
