baseResources:
    secrets:
        - name: ENC[AES256_GCM,data:XhtPI+HXO1IxwMBwEMQvHnwcBncSlVxO,iv:OR7BLUhND7tpEhe0YxS8K6hFRVakOUQEpEl27O8k080=,tag:Tk8AapxXxmjlquJNSMBa4w==,type:str]
          multilineFields:
            id_ed25519: ENC[AES256_GCM,data:yrJMOd7WMuq+D1ff24MKs9I9BaWaP/Lep15j8w7ON1H0vVtztB9AnL8fCIAp7HHigy/+D2gukPfIZHu7KGwzO3qRyQ4KVJBXpl3SoP2IdOnOFv1Mv4SYSvg0XZxRnJxkmBQbuZwQSIRq79p41VnemdiLuUCjgBMzTRVwsjr0Ddkjyv/N8AyWcIlMSH8Z6HS8K/kw+6UwG9s8YaYK9cJqcH3WgzL4A5RGC5G905X03CWzdX/1LVC746qTW6lAPZo+gWi5GUr7qbaFKCvMOI1piBEJ20DuYRSgKssuLT8lFZ65Wo9GObf7IF77MOpvziqAqD5BMwxDnF4BPyytPDPBSr8CUCsAh4GvGUsFOwcaQhf4yTN4+cjxxPmSb+Veuv7r/pn9ZvPhJfaAuLPzJt/OAfThp80DxS2vZ8d01aAxdyeRTYlfFZYK8hD4swWj8ftxyQObgSYm8H7rShPBT9N0DNqeUH/5AZiqcjqZSPJdV5EpzW5S7i4bUQbXgDaP0KriGSuK5m2zEdArZpIBdPZk7aJHviGhXOuRg4A=,iv:sghT6+5ajXyA4QQDZn4PqjohthPrggpfl93a23dDEnI=,tag:oauGI/piAs7jG1A9OzshQg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-08-03T21:03:05Z"
    mac: ENC[AES256_GCM,data:942amAZYQOKEszE1p+HfUI7RjsyXRp+9qUeXSP59WwWjrMFOJjRKF9Hlzh0fRUZtU1LHQa6cI0aAoFKk1ApyYb95v5zKPp2SAHZvi8RUk+flB8kpfzOabt6HSsE65r9cLFegRv6p0swmzW2U4fOn0jwP7j1pPZJ+p5TK1LScW5s=,iv:FU9QGQG/myZscYZaeVPH13FJdFrWQ2wC5ko3zd3v6KU=,tag:ch2H7aJZlCj6oDEffzSpEQ==,type:str]
    pgp:
        - created_at: "2023-08-03T21:03:04Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA1Biv9gnCd8SAQgAmxoehSyvxDeRrWUouXSzQ2zMgj5XgUIZrKQE5xG6oxPC
            iM9Ie2K4VmVW+w6xiujUFi1SyR/6w7nhqRA2PUPbKCp6qzGMPD+72zxhgcWXW+ig
            CObhTPQAKBKbOR1cHxxsk6+dVldYSQopp7h07akXDwosJNBzTNmDi2puAhbIyexG
            5JnlcF6uXLXAsNZTBlyk/WnGv2QYD1oG1UVJM7Q5Zv6Y6BtZzZyztevVEhgPqYdv
            v2l11Fu/TvdBgYMWY0Zizwob80iZQT4qwDRs79//5OnLunnbFQOGqQp/1Os2R5dy
            0aTImK9WDXQtgDF7q/XEfj00eJwKO2JIISUMkRhmr9JcAWrsFOSdEtCCNBVdJyH+
            ovG5Rx8OOxh7dgi/gT/4jlh4rpSmpPS3LdvqIa6FDEG37iH+b4OBCfct79VW1brX
            L3y494oN2+bZ5NTzY+EaKJiQIZ2bDzPk0QINpRM=
            =4gM4
            -----END PGP MESSAGE-----
          fp: 02B688797D1B649A6FB352756E8AC191164F2E1D
    unencrypted_suffix: _unencrypted
    version: 3.7.3
